### ISSUE TITLE
Config not working as expected in development

### ISSUE THREAD

**Issue by reefdog** [toptal/chewy#701] opened 2020-01-08 20:27 UTC
Hey folks. Unsure what's going awry here, so please let me know what else we can provide.

We're using Chewy 5.1.0 with Rails 5.2 and Ruby 2.5.7. For some reason, neither of the documented approaches for configuration (`config/chewy.yml` or an initializer with `Chewy.settings = {...}`) are working.

Specifically, we're trying to set `request_strategy` to `:bypass` in development using either of the documented approaches:

```yml
# config/chewy.yml
development:
  host: 'localhost'
  request_strategy: :bypass
  request_timeout: 300
```

```ruby
# config/initializers/chewy.rb
Chewy.settings = { request_strategy: :bypass }
```

But **neither one works** and it remains `:atomic`:

```
$ rails c
Chewy console strategy is `urgent`
Loading development environment (Rails 5.2.4.1)
irb(main):001:0> Chewy.request_strategy
=> :atomic
```

The only way we can get this to stick is with an initializer that assigns `Chewy.request_strategy` directly:

```ruby
# config/initializers/chewy.rb
Chewy.request_strategy = :bypass
```

Which then creates the expected result:
```
$ rails c
Chewy console strategy is `urgent`
Loading development environment (Rails 5.2.4.1)
irb(main):001:0> Chewy.request_strategy
=> :bypass
```

(And yes, I confirmed the Rails env is `development`.)

I'm assuming most people don't have trouble with config, or this would be a bigger deal. So any ideas for how we can figure out what's going on?

🙏

**Comment by jonatas** [comment] 2020-01-13 14:11
Hello @reefdog , can you please confirm that you're talking about `config/chewy.yml` and not `config/chewy.rb`?

**Comment by jonatas** [comment] 2020-01-13 14:17
I hacked some specs and looks like it's not using the `yaml` as a proper resource. Check the new specs I added:

```ruby
        expect(File).to receive(:exist?)
          .with(Pathname.new(__dir__).join('config', 'chewy.yml')).and_return(true)
        expect(File).to receive(:read).and_return(<<~YAML)
        development:
          request_strategy: :bypass
        YAML
        expect(subject.configuration[:request_strategy]).to eq(:bypass)
        expect(subject.request_strategy).to eq(:bypass)
```
and it fails in the last assertion.

**Comment by reefdog** [comment] 2020-01-13 15:34
@jonatas Gah, yes `config/chewy.yml` is my local config file. Apologies for the typo in my issue, I'll edit.

So your test proves that Chewy isn't correctly parsing config out of the YAML file, then?

**Comment by jonatas** [comment] 2020-01-13 20:10
Please fix it by using the file in the initializers folder as you suggested or submit a PR with the fix.

**Comment by reefdog** [comment] 2020-01-14 16:13
@jonatas I'm happy to look into contributing a fix, but I'm confused as to why the [documentation says to use `config/chewy.yml`](https://github.com/toptal/chewy#client-settings) if it doesn't work.

My assumption is that I was doing something wrong, but does configuration via YAML not work at all? If so, any idea why it's documented? Did it work at one point and then stop?

**Comment by reefdog** [comment] 2020-01-14 16:16
Also, note that we couldn't get _either_ of the two documented solutions to work. The docs say that we should use the initializer like so:

```ruby
# config/initializers/chewy.rb
Chewy.settings = { request_strategy: :bypass }
```

But we had to assign it directly, as documented in the original comment:

```ruby
# config/initializers/chewy.rb
Chewy.request_strategy = :bypass
```

**Comment by dalthon** [comment] 2021-02-19 16:48
This is a duplicate of https://github.com/toptal/chewy/issues/495

At rails console strategy `:urgent` is hardcoded.
https://github.com/toptal/chewy/blob/master/lib/chewy/railtie.rb#L49

We should change it

**Closed by dalthon** 2021-02-19 16:48 UTC
Labels: duplicate
